scala-js/scala-js-website

index.md

Added a link to one of my page that uses scala-js

Added Link to sumosim homepage

---

index.md

And rephrase the Resources section in general.

Add link to the Gitter chat room.

---

_posts/news/2015-02-05-announcing-scalajs-0.6.0.md
index.md

* Add a link to the front page along with other test frameworks.
* Specify dependency information for the project.

Update information of Greenlight project

---

index.md

sumosim is only one of the doctus exampleprojects

Replaced the link to sumosim by doctus

---

index.md

Added link to Paths.scala.js

---

index.md

While they're still works in progress, I believe they're now worth listing.

Adding jsext and jquery-facade to the listing

---

index.md

Now that it's in Beta and accepting users, it seems like it's time.

Added Querki to the project list

---

index.md

Fix #144: Added add-library instructions

---

index.md

I added links to my facades to the website

added several facades to the list

---

index.md

I was asked to make a PR for scalajs-velocity. I also had another couple of scalajs binding projects.

Adding 3 scalajs bindings

---

index.html

Also "system libraries" -> "standard libraries", as this is clearer what we mean.

Give TypeScript the reliable code completion bullet.

---

_data/library/scalalibs.yml

Add Each library

---

_config.yml
_includes/head.html
_includes/ogp.html
index.html

Added a site-wide og:description.

Fixed issues in OpenGraph meta tags.

---

_data/library/scalalibs.yml
_data/library/testlibs.yml
libraries/index.md
libraries/testing.md

Slight tidying up of the Libraries section.
The test-libs page now has less repetitive language and separates the libs from the frameworks. The lib-group index now looks much, much clearer.

Make community libraries clearer.

---

doc/project/js-environments.md

Updating the actual Node.js setup information into a more standardized way of handling the Node.js environments and setups in general. 
Before anyone says it.. Running shell scripts from the Internet:

Update Node.js information for Ubuntu

---

doc/project/cross-build.md

see https://github.com/scala-js/scala-js-website/issues/178

added section on scalajs-stubs

---

_data/library/jsfacades.yml

Also, updated the comment for jquery-facade, to reflect the fact that it's no longer conspicuously incomplete.

Updated version numbers for org.querki libraries

---

_data/library/scalalibs.yml

Updated version of jsext, and added a pointer to shocon.

Updated org.querki libraries

---

_config.yml
_data/doc.yml
_posts/news/2016-06-17-announcing-scalajs-0.6.10.md
doc/all-api.md
doc/internals/downloads.md
doc/internals/version-history.md

Still have to do the list of bug fixes.

Announcing Scala.js 0.6.10

---

_data/library/jsfacades.yml
_data/library/scalalibs.yml

Also added link to java-time JavaDoc for `scalajs-jsjoda`.

Add scalajs-jsjoda

---

_data/library/scalalibs.yml

Include scala-java-locales on the list of scala libraries

Scala-java-locales

---

_data/library/scalalibs.yml

Add reference to scalajs-java-logging on the libraries section

scalajs-java-logging

---

_data/library/scalalibs.yml

Updates from issues and on Akka.Js side to the libraries section.

Additions to libraries.

---

community/index.md

This is a continuation of #310

Add the Binding.scala • TodoMVC example

---

_data/library/scalalibs.yml

Add OutWatch framework

---

community/index.md

https://github.com/kschuetz/checkers

Add Checkers to open source projects list

---

_data/library/scalalibs.yml

http://repo1.maven.org/maven2/io/github/cquiroz/scala-java-locales_sjs0.6_2.11/

fix version number of scala-java-locales

---

_data/library/jsfacades.yml
_data/library/scalalibs.yml

Bumped js-joda version to 1.0.6.

---

_data/library/jsfacades.yml
_data/library/scalalibs.yml

It adds the following 3 libraries:
- scalajs-reactjs
- statictags
- scala-json-rpc
Close https://github.com/scala-js/scala-js-website/issues/337

Add 3 libraries

---

community/index.md

Hi,
i've added references to https://scastie.scala-lang.org and https://scalafiddle.io to community page.

 References to Scastie and Scalafiddle-editor at community page

---

tutorial/index.md

Skeletons/templates are another great way of starting to use Scala.js, so a link from the Tutorials page could be quite helpful for newcomers to the Scala.js ecosystem.

Link from tutorials page to skeletons

---

_data/library/jsfacades.yml
_data/library/scalalibs.yml

Bump version js-joda facade & java-time-drop-in to 1.1.2.

---

_data/library/scalalibs.yml

Note that I would also have added [kantan.regex](https://github.com/nrinaudo/kantan.regex), but it doesn't look like there's a good category for that kind of library yet.

Add kantan.csv to the list of Serializastion/pickling libraries

---

_data/doc.yml
doc/interoperability/exceptions.md

Add some exception interop documentation per #406.

Add documentation about exceptions across Scala.js/JavaScript

---

_data/library/jsfacades.yml

There are 4 different repositories (one for each facade). I hope it is not too verbose.

Add scaladget facades

---

_data/library/scalalibs.yml

This adds the EvilPlot plotting library to the libraries page.
Closes #417

Add EvilPlot to the libraries page.

---

doc/interoperability/facade-types.md

object Bar has @js.native annotation, should extends js.Any

Fix JSImport example

---

libraries/skeletons.md

Someone asked for the project to be more advertised, and nowhere is better than the website itself.

Added Scala Google Spreadsheets as skeleton project

---

.gitignore
.travis.yml
Gemfile
README.md

I wanted to contribute and normally to do that I'd check out the content,
and get into some sort of feedback loop where I view the output, make
changes and iterate. I was unable to do this however as I am unfamiliar
with the Ruby/Jekyll ecosystem.
Based on the travis.yml file (it's great to have it!), I established
that as part of the set up we need to install RVM, set up bundler and
all the necessary dependencies.
I moved out the dependencies into the standard Gemfile approach of the
Ruby ecosystem.
This works on Ubuntu 18 and the Windows Subsystem for Linux.
Now I'm able to edit and see the impact of my changes immediately and
without problem :-)... and I hope the future contributor wil lbe able to
do the same.

Make it clearer how to contribute

---

doc/tutorial/index.md

Source: root/doc/tutorial/index
Destination: root/libraries/skeletons

Update link to skeletons in tutorial

---

_data/library/testlibs.yml

https://wvlet.org/airframe/docs/airspec

Add AirSpec testing framework

---

libraries/skeletons.md

Link to a skeleton I've made to help create Scala.js & Play Framework web applications with some functionalities (authorization, hashing, RPC, zxcvbn, etc.). It is evolving, hope to find some time to create git documentations.

Add skeleton with Play, Scala.js and React

---

libraries/skeletons.md

Add a skeleton for creating AWS Lambdas using Scala.js 1.0

Add AWS Lambda skeleton

---

doc/interoperability/global-scope.md

See also https://github.com/scala-js/scala-js/issues/3685.

Refer to fileLevelThis instead of globalThis

---

_data/testimonials.yml

One of the people no longer has a linked in img, not sure what to do there (Clint i think)

Update broken testimonial links

---

_data/library/scalalibs.yml

Just updating the link as we have an actual website now

Update Laminar library website URL

---

doc/project/module.md

This is more or less a copy from the 1.3.0 release notes.

Document module splitting

---

_data/library/scalalibs.yml

- **Name**: _Linden_
- **Url**: _[linden.dongoteam.hu](https://linden.dongoteam.hu)_
- **Description**: _Functional reactive frontend framework_
- **Dependency**:
```
resolvers += "DongoTeam repository" at "https://public.repository.dongoteam.hu"
libraryDependencies += "org.dongoteam.linden" %%% "linden-package-flowers" % "<version>"
```

Add Linden library into `Web libraries/frameworks`

---

_data/library/scalalibs.yml

So what will convince you that Scala.js is more than "A safer way to build robust front-end web applications!" 😉

Add several typelevel libs

---

community/presentations.md

Update community -> presentations section

---

_config.yml
index.html

Inspired by this blurb on the Scala Center "First Five Years" report.
> Scala.js targets any JavaScript environment, from browsers to Node.js servers to embedded devices. Using Scala.js, developers can leverage Scala, its libraries, as well as the JavaScript ecosystem, to develop robust applications that run anywhere.
https://scala.epfl.ch/records/first-five-years/report#tech
I attempted to condense it. Here's a couple proposals. feedback and revisions very welcome, etc. etc. :)
> Harness the Scala and JavaScript ecosystems to develop robust apps. Rrun in browsers, serverless, Node.js. Anywhere.
> Harness the Scala and JavaScript ecosystems together. Develop robust apps that run in browsers, serverless, Node.js. Anywhere.
Not sure how important this "anywhere" is 🤔 
Thanks!

Scala.js beyond the browser

---

doc/project/module.md

PR for documentation change suggested in https://github.com/scala-js/scala-js/issues/3893#issuecomment-1604090346

Document ES module limitation in fullOpt

---

community/presentations.md

Hi,
Maybe someone will benefit from this talk :)
Best regards

Add presentation entry

---

doc/project/cross-build.md
doc/tutorial/basic/index.md

2.13.1 is really old and may have compatibility problems with current JDKs and lord knows what else
this came up today on Discord in #scala-users

don't recommend very old Scala version

---

_data/library/testlibs.yml

add mUnit to the list of suggested test frameworks

---

doc/project/webassembly.md

Unless the original title was intentional?

Update webassembly.md to use correct title
