- index.md
The list of libraries has become too big and too random. This hopefully makes it more useful by categorizing the libraries, and only providing one-line descriptions. sbt details should be found on the libraries' respective readmes.
> Condense and organize the list of libraries.

- _posts/news/2015-01-23-announcing-scalajs-0.6.0-RC2.md
- doc/index.md
- downloads.md
- index.md
To be announced tomorrow (January 23) morning (CET).
> Announcing Scala.js 0.6.0-RC2.

- _posts/news/2015-02-05-announcing-scalajs-0.6.0.md
I think people will still probably be following links to the 0.6.0 announcement. The lack of the following libraries might imply that they aren't updated yet.
> Belatedly updated 0.6.0 announcement with more published libs

- _config.yml
- _posts/news/2015-03-16-announcing-scalajs-0.6.2.md
- doc/index.md
- downloads.md
- index.md
To be announced tomorrow morning CET, if all goes well.
> Announcing Scala.js 0.6.2.

- index.md
Add [scalajs-createjs](https://github.com/takezoe/scalajs-createjs) and [scalajs-ace](https://github.com/takezoe/scalajs-ace) to Static types for JavaScript libraries section.
> Add scalajs-createjs and scalajs-ace

- index.md
I noticed scala-parser-combinators has been cross-compiled too (http://mvnrepository.com/artifact/org.scala-js/scala-parser-combinators_sjs0.6_2.11/1.0.2), but I don't see any readme or docs anywhere, so not sure if we should add those as well.
> Add FastParse to list of libraries

- index.md
[scalajs-createjs](https://github.com/scalawarrior/scalajs-createjs) and [scalars-ace](https://github.com/scalawarrior/scalajs-ace) has been moved to @scalawarrior organization.
So I want to fix these URLs in `index.md`.
> Move scalajs-createjs and scalars-ace to scalawarrior organization

- _config.yml
- _posts/news/2015-08-31-announcing-scalajs-0.6.5.md
- doc/calling-javascript.md
- doc/index.md
- doc/js-interoperability.md
- doc/sjs-defined-js-classes.md
- downloads.md
- index.md
The announcement is scheduled for Monday 31st morning CEST, assuming everything goes well with the release process.
> Update the docs for 0.6.5 and announce its release.

- index.md
Added scaladget library. Hope it could help.
> Add scaladget library

- community/index.md
The pointer under "Open Source Scala.js projects" ought to point to the source code, which is more in keeping with that section.
> Changed one of the Querki pointers

- doc/interoperability/types.md
From a PR for last website #153
adding Literal object construction using an scala object interface section to address http://stackoverflow.com/questions/26638171/how-do-i-create-options-objects-in-scala-js
Fix #152: Document option object pattern
> Fix #152: Document option object pattern for new website

- _assets/js/bundle.js
- _data/library/jsfacades.yml
- _data/library/scalalibs.yml
- _includes/nav.html
- community/index.md
Fixes #179, #184, #192, #194, #202 and #195.
> New libraries added.

- community/index.md
Right now "Testimonials" header is not really a header. This simple change fixes it
> Testimonials header fixed

- _data/library/scalalibs.yml
* Moved `NICTA/rng` from "Common" to "Misc" section (it's not common at all).
* Added @lihaoyi 's Workbench
* Added scalajs-benchmark
* Give Scala-Async an actual description (just copied from their GH page).
* Give Nyaya-Gen a `dep` entry.
> Update "Scala libraries" page

- _data/library/scalalibs.yml
Recently we open-sourced [Binding.scala](https://github.com/ThoughtWorksInc/Binding.scala), which is a data-binding framework for [Scala](http://www.scala-lang.org/) JVM and [Scala.js](http://www.scala-js.org/).
Binding.scala can be used as a **[reactive](https://en.wikipedia.org/wiki/Reactive_programming) web framework**.
It enables you use native XML literal syntax to create reactive DOM nodes,
which are able to automatically change whenever the data source changes.
> Add Binding.scala

- doc/interoperability/facade-types.md
See also https://github.com/scala-js/scala-js/issues/1892
> Fix #203: Remove the js.GlobalScope package object example.

- _config.yml
- _posts/news/2016-01-25-announcing-scalajs-0.6.6.md
- doc/all-api.md
- doc/internals/downloads.md
- doc/interoperability/sjs-defined-js-classes.md
- doc/project/building.md
- doc/project/js-environments.md
- tutorial/basic/index.md
Scaladoc for the library of 0.6.6 available at http://www.scala-js.org/api/scalajs-library/0.6.6/#scala.scalajs.js.package
> Update the documentation for 0.6.6 and announce it.

- .travis.yml
The latest Jekyll 3.1.0 apparently broke something.
> Lock the versions of the gems we install on Travis.

- .travis.yml
Since now scala-js.org resolves to the CDN's caching servers, which do not like ssh connections.
> Use origin.scala-js.org for deployment.

- _includes/docnav.html
Scala.js shields use HTTPS instead of HTTP.
> Doc nav is now fully open to reveal all doc pages.

- _assets/css/style.scss
- index.html
Not ideal, but at least visible
> Fix #196: Add the Scala.js version on the front page.

- doc/project/building.md
Added configuration "Compile" to command that sets mainClass. Also added a brief explanation and links to two relevant Stack Overflow questions.
> Added configuration "Compile" to command that sets mainClass.

- _data/library/jsfacades.yml
- tutorial/basic/index.md
New commit history for the tutorial repo available at https://github.com/scala-js/scalajs-tutorial/commits/develop
> Update the tutorial for DOM and jQuery 0.9.0.

- doc/interoperability/facade-types.md
I'm guessing these were from before the `scala.js` -> `scala.scalajs.js` package rename
> Fix package name for annotations

- .travis.yml
- _assets/css/style.scss
- _assets/js/bundle.js
- _assets/js/custom.js
- _assets/js/lunr.js
- _config.yml
- _includes/footer.html
- _includes/js.html
- _includes/nav.html
- _layouts/default.html
- _plugins/tokenize.rb
- search_data.json
JS loading is deferred until after page render.
Note: .json compression must be enabled before merging this due to the large size of the search index.json
> Implemented local search with lunr.js

- _data/library/scalalibs.yml
start official support since 7.2.1
- https://github.com/scalaz/scalaz/pull/1111
- https://github.com/scalaz/scalaz/wiki/7.2.1
- https://groups.google.com/d/topic/scalaz/NPOdiT9lv-E/discussion
> update scalaz url and dep

- .htaccess
- _data/doc.yml
- doc/project/testing.md
Adding testing page to documentation explaining unit testing in cross project as well as how to configure integration testing in cross project. Let me know what you think. /cc @ochrons
> Testing section

- libraries/skeletons.md
PR created as per Otto Chrons' suggestion on https://gitter.im/scala-js/scala-js:
"**ochrons Mar 17 07:26** @aholland you should raise an issue/PR on scala-js-website to get that included on the site".
My concerns are
(1) Why does the other reference to Play (directly above mine) have an exclamation mark? Should mine also, or show that one not be there, or don't we care?
(2) Is my explanation too long?
Thanks,
Anthony
> Insert reference to new skeleton, play-scalajs-workbench-example

- _includes/library.html
On my computer, I see a literal `</img>` string after the clipboard image on the [libraries page](https://www.scala-js.org/libraries/libs.html):
> Remove </img> after clipboard image

- _data/library/testlibs.yml
InTheNow removed his GitHub user, so zcheck no longer exists. The closest is https://github.com/Nuriaion/zcheck, which was probably a fork, and doesn't contain the code for version 0.6.1
> Remove zcheck from test libs

- _data/library/jsfacades.yml
Note: I have not tested this, nor have I tested the library, but it looks to be somewhat well along and it is for an important library.
> added entry for Paper-Scala-js binding

- doc/interoperability/index.md
- doc/sjs-for-js/index.md
* Fixes inconsistent semicolon usage in ES6 examples.
* Adds `xhr.send()`: I am aware that making the example longer is not desirable. However, this one additional line makes it more well rounded. Specifically, it prevents other copy/pasters from falling into the "why the hell is my listener not executing?!" trap.
> Improve ES6 vs. Scala.js examples

- tutorial/basic/index.md
Originally, I just was looking to update the dependency version of `scalajs-jquery` to be a 2.12 compatible version.  Looking at history it appears that the tutorial tends to be on the latest for libraries, and I figure it that eventually it will want switch to 2.12, so I updated everything.
I ran through the tutorial myself using these 2.12 and these versions.  I then switched to a clone on 2.11.8 and saw the new library versions also worked fine there.
> Tutorial: Update to Scala 2.12 and latest libraries

- _data/library/scalalibs.yml
The project recently moved to circe/circe and is now at version 0.6.1.
> Update circe project link and deps

- _data/library/scalalibs.yml
Points to the latest versions of both libraries
Note that `scala-java-time` has changed organization
> Updated versions of scala-java-locales and scala-java-time

- _data/library/scalalibs.yml
Note that squants now lives under `org.typelevel`
> Update to the latest squants release

- _data/library/scalalibs.yml
A very small correction to the link/button on the page as the Monocle now has been ported to sjs.
> Updated the scalalibs.yaml to reference the real Monocle 

- _data/library/scalalibs.yml
https://github.com/wvlet/log, a java.util.logging extension, now supports Scala.js.
> Add wvlet-log to library list

- _data/library/jsfacades.yml
scalajs-reactjs now includes facade for react-redux too. This updates the description so that it communicates what's actually included.
> Update description for scalajs-reactjs

- _data/library/jsfacades.yml
Upadate Scaladget version and content (now wraps bootstrap-native js lib rather than bootstrap lib)
> Update scaladget javascript library

- _data/library/scalalibs.yml
I'd like to create an additional topic for dependency injection libraries, now that we have two types of DI libraries that support Scala.js (runtime vs compile-time).
> Add DI library that supports Scala.js

- _config.yml
- _posts/news/2017-07-29-announcing-scalajs-0.6.19.md
- doc/all-api.md
- doc/internals/downloads.md
- doc/internals/version-history.md
To be announced tomorrow, end of day probably.
> Announcing Scala.js 0.6.19.

- _config.yml
- _posts/news/2017-09-01-announcing-scalajs-0.6.20.md
- doc/all-api.md
- doc/internals/downloads.md
- doc/internals/version-history.md
- doc/project/building.md
- doc/project/js-environments.md
- doc/project/testing.md
- tutorial/basic/index.md
To be announced sometime tomorrow, if all goes well.
> Announcing Scala.js 0.6.20.

- _config.yml
- _posts/news/2017-11-06-announcing-scalajs-0.6.21.md
- doc/all-api.md
- doc/internals/downloads.md
- doc/internals/version-history.md
TBA tomorrow (Saturday) sometime during the day.
> Announcing Scala.js 0.6.21.

- community/index.md
Adding OhMyCoin (http://ohmyco.in) to the list of community projects.
I am removing Insightware (which I created too) as it is no longer active and it's a broken link.
> Replace Insightware (no longer active) with OhMyCoin in community usages

- _config.yml
- _posts/news/2018-01-24-announcing-scalajs-0.6.22.md
- doc/all-api.md
- doc/internals/downloads.md
- doc/internals/version-history.md
To be announced sometime tomorrow January 24.
> Announcing Scala.js 0.6.22.

- doc/project/cross-build.md
I was confused about why a cross-project build was packaging SJSIR JARs for my JVM project until I realized that I should not include `enablePlugins(ScalaJSPlugin)` on my cross project build. Hopefully adding this line to the documentation to make it more clear saves someone else some time. (Fixes #394, which I just discovered!)
> Fix #394: clarify sbt plugins for cross-project builds

- _data/library/jsfacades.yml
- tutorial/basic/index.md
We keep telling people that jquery-facade is better maintained than scalajs-jquery and is the recommended library for jQuery, but our tutorial was still using scalajs-jquery, setting users on the wrong path.
In the process, we also upgrade to the latest versions of scalajs-dom and uTest.
The PR also removes scalajs-jquery from the list of facade libraries.
The updated tutorial repo can be seen in [the `develop` branch](https://github.com/scala-js/scalajs-tutorial/commits/develop), for review.
> Use jquery-facade instead of scalajs-jquery in the tutorial.

- doc/sjs-for-js/es6-to-scala-part2.md
The code in the example doesn't work since `Map.flatMap` returns a `Map` (on a tuple with 2 elements) so only the last score will be taken into consideration. The code below will return `("Jane", 200)` but it should be `("John", 1000)`
Making the flatMap return a list will return the list of tuple scores as intended.
```
val scores =
mutable.Map.empty[String, mutable.Buffer[Int]]
def addScore(player: String, score: Int): Unit = {
scores.getOrElseUpdate(player, mutable.Buffer())
.append(score)
}
def bestScore: (String, Int) = {
val all = scores.flatMap {
case (player, pScores) =>
pScores.map(s => (player, s))
}
if (all.isEmpty)
("", 0)
else
all.maxBy(_._2)
}
def averageScore: Int = {
val allScores = scores.flatMap(_._2)
if (allScores.isEmpty)
0
else
allScores.sum / allScores.size
} …
```
> Fix the computation of `bestScore` in an example.

- _data/library/testlibs.yml
I added the `enablePlugins` incantation to add support for the library in sbt, as the rest of dependencies assume sbt too.
Followed the instructions in https://www.scala-js.org/news/2016/01/25/announcing-scalajs-0.6.6/
> Add JUnit to supported testing libs

- _config.yml
- _posts/news/2018-11-29-announcing-scalajs-0.6.26.md
- doc/all-api.md
- doc/internals/downloads.md
- doc/internals/version-history.md
- doc/interoperability/export-to-javascript.md
- doc/project/module.md
And update the documentation for the support of ECMAScript modules.
> Announcing Scala.js 0.6.26.

- _layouts/post.html
The page title is already inserted by `wrap.html`. It shouldn't be repeated in the `post` layout.
> Fix the double title in News page.

- _data/library/scalalibs.yml
Hi, I made these libraries specifically for Scala.js. I would appreciate to have them included on https://www.scala-js.org/libraries/libs.html now that they've matured quite a bit.
Note: I put my _Scala DOM Types_ library together with other similar libraries within the "Web" category (as opposed to the end of the category), hope that's ok.
> Add Laminar, Airstream, Scala DOM Types libraries

- doc/sjs-for-js/es6-to-scala-part3.md
self explanatory the current signature doesn't work.
> Fix the signature of `def parse` in an example.

- _data/doc.yml
- doc/project/linking-errors.md
Related to https://github.com/scala-js/scala-js/pull/3751
> Document causes of linking errors and how to fix them.

- _config.yml
- _posts/news/2019-11-21-announcing-scalajs-0.6.31.md
- doc/all-api.md
- doc/internals/downloads.md
- doc/internals/version-history.md
> Announcing Scala.js 0.6.31.

- doc/interoperability/facade-types.md
- doc/project/module.md
The new documentation was copied from the release nodes of Scala.js 0.6.26.
> Add more documentation about using ES modules.

- _config.yml
- _posts/news/2020-01-24-announcing-scalajs-0.6.32.md
- doc/all-api.md
- doc/internals/downloads.md
- doc/internals/version-history.md
Optimistically targeted for announcing today.
> Announcing Scala.js 0.6.32.

- doc/tutorial/basic/index.md
- index.html
* sbt 1.3.7, Scala 2.13.1, scalajs-dom 0.9.8, uTest 0.7.4.
* Go back to scalajs-jquery because jquery-facade was not updated for Scala 2.13.
* Update the links to downloads for sbt.
* Mention Metals instead of Eclipse.
These changes go with the history at https://github.com/scala-js/scalajs-tutorial/commits/develop
> Modernize the basic tutorial.

- _config.yml
- _data/doc.yml
- _posts/news/2020-02-25-announcing-scalajs-1.0.0.md
- doc/all-api.md
- doc/api.md
- doc/internals/downloads.md
- doc/internals/version-history.md
- doc/project/dependencies.md
- doc/project/js-environments.md
- doc/tutorial/basic/0.6.x.md
And update the website to use 1.x by default everywhere.
The tutorial is duplicated, with one version for 1.x (the default), and a legacy version for 0.6.x.
---
Not to be merged yet, but review welcome :)
> Announcing Scala.js 1.0.0.

- doc/interoperability/facade-types.md
- doc/interoperability/sjs-defined-js-classes.md
- doc/interoperability/types.md
- doc/project/building.md
- doc/project/js-environments.md
I noticed that a few API links were broken, so here's a PR to fix them.
Some parts of the documentation might need to be rewritten for 1.0.0. I only fixed the links I could fix; if I didn't find something in the 1.0.0 API docs, I didn't fix the link.
> Fix API links for Scala.js 1.0.0

- _config.yml
- _posts/news/2020-03-10-announcing-scalajs-1.0.1.md
- doc/all-api.md
- doc/internals/version-history.md
Note: this does not contain new links for downloads of the CLI. We need to figure out a process for building and uploading the CLI post-1.0.0.
> Announcing Scala.js 1.0.1.

- doc/semantics.md
In Scala.js 1.x `CheckedBehavior` is under `org.scalajs.linker.interface.CheckedBehavior`, and no longer `org.scalajs.core.tools.sem.CheckedBehavior`. This PR updates the website's documentation to reflect that.
> Fix instanceOfs linker config for Scala.js 1.x

- doc/api.md
They now have their own repos with their own API hosting.
> Remove the links to the latest APIs for JS envs and logging.

- _posts/news/2020-05-18-announcing-scalajs-1.1.0.md
scala-js/scala-js#3283 was not classified into the right
milestone. Therefore, when we assembled the release notes, we forgot
about it.
> Add fastOptJS invalidation on config change to 1.1.0 release notes

- doc/tutorial/basic/0.6.x.md
- doc/tutorial/basic/index.md
Prompted by a SO [question](https://stackoverflow.com/questions/64393465/how-can-i-get-the-scala-js-1-3-0-tutorial-to-run-part-2/64394115#64394115). Some people will try to run the complete app in the github repo before reading the tutorial in full, so I figured we could mention the need for jsdom more prominently, in the prerequisites section.
> Basic tutorial: mention jsdom prerequisite upfront

- doc/tutorial/basic/index.md
This basically means:
- Using xLinkJS instead of xOptJS
- Include JS code from the linked directory
> Update tutorial for Scala.js 1.3.x

- doc/project/building.md
- doc/project/linking-errors.md
- doc/project/module.md
- doc/project/testing.md
- doc/semantics.md
As a side effect, update the Node.js ES module support section.
> Update documentation for 1.3.x

- doc/project/index.md
It says its not maintained. Reference the tutorial instead.
> Do not reference boostrapping skeleton anymore

- doc/sjs-for-js/es6-to-scala-part2.md
ES6 `Symbol`s can be used as object keys.
> Doc: `symbol`s are valid object keys

- doc/sjs-for-js/es6-to-scala-part2.md
JS has an `includes` method on arrays instead of the deprecated `indexOf() === -1`, and `drop` works like `slice` (theoretically `.dropRight(n)` == `.slice(0, -n)`)
> Doc: Adds `Array#includes` and `Array#slice`

- doc/index.md
The sbt link was obsolete.
Also updated Oracle link, although the previous link is still forwarded to the JDK 8 section.
I just wanted to find the latest version number for scala-js, which is buried at the basic tutorial.
The old sbt link made me think I was on an old doc page, so I despaired.
There is an effort underway to make the beginner experience less confusing, which should mitigate the despairing.
> Update links on doc landing page

- _config.yml
- _posts/news/2022-02-14-announcing-scalajs-1.9.0.md
- doc/all-api.md
- doc/internals/version-history.md
- doc/semantics.md
- libraries/index.md
To be merged later, once it is published.
> Announcing Scala.js 1.9.0.

- doc/project/cross-build.md
Hi :)
The cross build docs refer to scalajs-stubs 1.0.0, but 1.10 is already out. Also, 1.0.0 is not published for scala 3, which is why I noticed it at all.
This PR just bumps the version
> Refer to scalajs-stubs 1.1.0 instead of 1.0.0 in cross build docs

- _config.yml
- _posts/news/2022-04-04-announcing-scalajs-1.10.0.md
- doc/all-api.md
- doc/internals/version-history.md
- doc/project/module.md
> Announcing Scala.js 1.10.0.

- _config.yml
- _posts/news/2022-06-25-announcing-scalajs-1.10.1.md
- doc/all-api.md
- doc/internals/version-history.md
To be merged only when it's out, but it can be reviewed already.
> Announcing Scala.js 1.10.1.

- index.html
Instead of ScalaFiddle, which is unfortunately offline.
@yurique Does that look good to you?
> Link to yurique's Scribble from the front page.

- .htaccess
- _posts/news/2021-04-01-announcing-scalajs-1.5.1.md
This is the URI referenced in https://github.com/scala-js/scala-js-website/blob/main/doc/internals/version-history.md
> Fix the permalink for 1.5.1

- _data/library/scalalibs.yml
The Slinky link listed on the Scala.js website is unable to access now
> Update Slinky homepage link

- community/index.md
Let's include more Scala.js projects.
> Update community -> projects section

- .asset-cache/.gitkeep
- Dockerfile
- README.md
- _site/.gitkeep
- docker-compose.yml
Based off #600.
I can't run Ruby 2.7.x on my machine anymore. Docker was the only solution I found. It may help others getting started to contribute to this website as well.
The setup is inspired by that of `scala-lang.org`, but modified to avoid UID hacker (instead has some volume hackery).
> Add a Docker-based setup.

- _config.yml
- _posts/news/2023-04-10-announcing-scalajs-1.13.1.md
- doc/all-api.md
- doc/internals/version-history.md
Not for until 1.13.1 is out, obviously. Taking a head start with writing the release notes.
This assumes that the last few issues for which there are pending PRs will be addressed before we release.
> Announcing Scala.js 1.13.1.

- docker-compose.yml
By default, published docker ports "bind" to all inbound addresses. We restrict to localhost to avoid exposing the site to the internet.
Note that malicious same L2 participants can still reach the container due to:
https://github.com/moby/moby/issues/45610
> Do not expose generated dev docker site to the internet

- doc/tutorial/basic/index.md
A student of mine noticed that the first npm package installed is `source-map-support `. Moved the generation of the package.json up in the tutorial.
> tutorial: Create a `package.json` in an earlier step

- doc/project/js-environments.md
- doc/tutorial/basic/index.md
Adding details of Playwright based js environment.
> Add playwright to js-environments

- doc/project/js-environments.md
The `scala-js-env-playwright` is updated to `v0.1.11`. 
Release notes : https://github.com/gmkumar2005/scala-js-env-playwright/releases/tag/v0.1.11
> Updates related to scala-js-env-playwright v0.1.11 release

- doc/project/cross-build.md
As of writing the latest version of sbt-scalajs-crossproject is 1.2.0 as listed on the repository of sbt-crossproject https://github.com/portable-scala/sbt-crossproject. This is a helpful change as being on 1.0.0 can introduce errors.
> Change scalajs-crossproject version to 1.2.0

- _config.yml
- doc/tutorial/laminar.md
- doc/tutorial/scalablytyped.md
- doc/tutorial/scalajs-vite.md
> Upgrades in the Vite-Laminar-ScalablyTyped tutorial.

- doc/project/webassembly.md
This was removed as part of v8 13.x.x ([changeset](https://chromium-review.googlesource.com/c/v8/v8/+/6074953), [discussion](https://issues.chromium.org/issues/382509286)).
Node.js 24.0.0 includes this version of v8, so specifying `--turboshaft-wasm` will cause Node to exit with `bad option: --turboshaft-wasm`
> Mention that `--turboshaft-wasm` is Node.js 23.x.x only
